export const groupACountries = [
  "Algeria", "Angola", "Antigua and Barbuda", "Argentina", "Armenia", "Aruba", "Azerbaijan", "Bahrain", "Bangladesh",
  "Belize", "Benin", "Bhutan", "Bolivia", "Botswana", "Brunei Darussalam", "Burkina Faso", "Burundi", "Cambodia",
  "Cameroon", "Cape Verde", "Chad", "Chile", "Colombia", "Comoros", "Costa Rica", "Côte d’Ivoire", "Djibouti",
  "Dominica", "Dominican Republic", "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Eswatini",
  "Ethiopia", "Gabon", "Gambia", "Georgia", "Ghana", "Grenada", "Guatemala", "Guernsey", "Guinea", "Guinea-Bissau",
  "Guyana", "Honduras", "Indonesia", "Isle of Man", "Jamaica", "Jersey", "Kazakhstan", "Kenya", "Kuwait",
  "Kyrgyzstan", "Laos", "Lebanon", "Lesotho", "Liberia", "Libya", "Macao", "Madagascar", "Malawi", "Maldives",
  "Mauritania", "Montenegro", "Montserrat", "Morocco", "Mongolia", "Mozambique", "Nauru", "Nepal", "Niger", "Oman",
  "Pakistan", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Qatar", "Republic of Moldova",
  "Saint Kitts and Nevis", "Saint Lucia", "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia",
  "Sierra Leone", "Solomon Islands", "South Africa", "Sri Lanka", "Suriname", "Tajikistan", "Tanzania", "Thailand",
  "Timor-Leste", "Togo", "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan", "Uganda",
  "United Arab Emirates", "Uzbekistan", "Venezuela", "Vietnam", "Zambia", "Zimbabwe"
];



export const groupBCountries = [
  "Afghanistan",
  "Albania",
  "Andorra",
  "Anguilla",
  "Antarctica",
  "Australia",
  "Austria",
  "Bahamas",
  "Barbados",
  "Belarus",
  "Belgium",
  "Bosnia and Herzegovina",
  "Brazil",
  "Bulgaria",
  "Burma",
  "Cabo Verde",
  "Central African Republic",
  "China",
  "Congo (Congo-Brazzaville)",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Democratic Republic of the Congo",
  "Denmark",
  "Estonia",
  "Fiji",
  "Finland",
  "France",
  "Germany",
  "Greece",
  "Greenland",
  "Haiti",
  "Hungary",
  "Iceland",
  "India",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Japan",
  "Jordan",
  "Kiribati",
  "Latvia",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Malaysia",
  "Malta",
  "Marshall Islands",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Monaco",
  "Myanmar (Burma)",
  "Namibia",
  "Netherlands",
  "New Zealand",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Palau",
  "Palestine",
  "Poland",
  "Portugal",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Seychelles",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Somalia",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sudan",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tuvalu",
  "Ukraine",
  "United Kingdom",
  "Uruguay",
  "Vanuatu",
  "Vatican City",
  "Yemen",
  "UK",
  "United KingFdom",
  "Great Britain",
  "Britain",
  "England",
  "Scotland",
  "Wales",
  "Northern Ireland",
  "GB",
  "U.K.",
  "U.K",
  "U.K",
  "FRG",
  "Bharat",
  "Canada"
];


export const groupCCountries = [
  "USA",
  "U.S.A",
  "U.S.",
  "United States",
  "United States of America",
  "America",
  "US",
  "The States",
  "United States America"
];


export const groupDcountries = [
    "Nigeria"
]






